learningai/lib/learningai_web/router.ex
defmodule LearningaiWeb.Router do
  use LearningaiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug LearningaiWeb.Plugs.SetUser

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LearningaiWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/courses", CourseController do
      resources "/contents", ContentController
    end
  end

  scope "/auth", LearningaiWeb do
    pipe_through :browser
    get "/signout", AuthController, :signout
    # for path /auth/github. the "request" function is defined automatically
     get "/:provider", AuthController, :request
     # for return back from github
     get "/:provider/callback", AuthController, :callback
  end

  # scope "/courses/:course_id/", LearningaiWeb do
  #   pipe_through :browser
  #   resources "/coursecontents", CourseContentController
  # end

  # Other scopes may use custom stacks.
  # scope "/api", LearningaiWeb do
  #   pipe_through :api
  # end
end

learningai/lib/learningai/instructors/course.ex
defmodule Learningai.Instructors.Course do
  use Ecto.Schema
  import Ecto.Changeset
  alias Learningai.Instructors.Course


  schema "courses" do
    field :name, :string
    belongs_to :user, Learningai.User
    timestamps()
  end

  @doc false
  def changeset(%Course{} = course, attrs) do
    course
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

learningai/lib/learningai_web/controllers/course_controller.ex
  defmodule LearningaiWeb.CourseController do
  use LearningaiWeb, :controller

  alias Learningai.Instructors
  alias Learningai.Instructors.Course
  alias Learningai.Repo

  plug LearningaiWeb.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete ]
  plug :check_course_owner when action in [:update, :edit, :delete]

  def index(conn, _params) do
    courses = Instructors.list_courses()
    render(conn, "index.html", courses: courses)
  end

  def new(conn, _params) do
    changeset = Instructors.change_course(%Course{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"course" => course_params}) do
    #case Instructors.create_course(course_params) do
    case Instructors.create_course_with_user(conn.assigns.user, course_params) do
      {:ok, course} ->
        conn
        |> put_flash(:info, "Course created successfully.")
        |> redirect(to: course_path(conn, :show, course))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    course = Instructors.get_course!(id)
    render(conn, "show.html", course: course)
  end

  def edit(conn, %{"id" => id}) do
    course = Instructors.get_course!(id)
    changeset = Instructors.change_course(course)
    render(conn, "edit.html", course: course, changeset: changeset)
    #render(conn, "edit_content.html", course: course, changeset: changeset)

  end

  def update(conn, %{"id" => id, "course" => course_params}) do
    course = Instructors.get_course!(id)

    case Instructors.update_course(course, course_params) do
      {:ok, course} ->
        conn
        |> put_flash(:info, "Course updated successfully.")
        |> redirect(to: course_path(conn, :show, course))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", course: course, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    course = Instructors.get_course!(id)
    {:ok, _course} = Instructors.delete_course(course)

    conn
    |> put_flash(:info, "Course deleted successfully.")
    |> redirect(to: course_path(conn, :index))
  end

  def check_course_owner(conn, _plugparams) do
    #This :params is courtesy "resource" controller helper. It pulls "id" out of the url and attach it to connect   
    # object under params.id property
    %{params: %{"id" => course_id}} = conn

    #Fetch the user id for the course id specified in the url and see if it equals the current user id,
    #let connection through, else reject
    if Repo.get(Course, course_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You cannot modify  that")
      |> redirect(to: course_path(conn, :index))
      |> halt()

    end
  end

end

learningai/lib/learningai_web/views/course_view.ex
defmodule LearningaiWeb.CourseView do
  use LearningaiWeb, :view
end

learningai/lib/learningai_web/templates/course/edit.html.eex
<h2>Edit Course</h2>

<%= render "form.html", Map.put(assigns, :action, course_path(@conn, :update, @course)) %>

<span><%= link "Back", to: course_path(@conn, :index) %></span>

learningai/lib/learningai_web/templates/course/edit_content.html.eex
<h2>@course.name</h2>
<span><%= link "Add Chapter", to: course_path(@conn, :add_chapter, @course) %> </span>
<span><%= link "Back", to: course_path(@conn, :index) %>  %></span>
<%= render "form.html", Map.put(assigns, :action, course_path(@conn, :update, @course)) %>

<span><%= link "Back", to: course_path(@conn, :index) %></span>

learningai/lib/learningai_web/templates/course/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

learningai/lib/learningai_web/templates/course/index.html.eex
<h2>Listing Courses</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for course <- @courses do %>
    <tr>
      <td><%= course.name %></td>
      <%= if @conn.assigns.user != nil do %>
        <%= if @conn.assigns.user.id == course.user_id do %>
          <td class="text-right">
            <span><%= link "NewContent", to: course_content_path(@conn, :new, course), class: "btn btn-primary btn-xs" %></span>
            <span><%= link "Show", to: course_content_path(@conn, :index, course), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Edit", to: course_path(@conn, :edit, course), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Delete", to: course_path(@conn, :delete, course), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
          </td>
        <% end %>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Course", to: course_path(@conn, :new) %></span>

learningai/lib/learningai_web/templates/course/new.html.eex
<h2>New Course</h2>

<%= render "form.html", Map.put(assigns, :action, course_path(@conn, :create)) %>

<span><%= link "Back", to: course_path(@conn, :index) %></span>

learningai/lib/learningai_web/templates/course/show.html.eex
<span><%= link "New Content", to: course_content_path(@conn, :new, @course) %></span>
<br/>
<br/>
<br/>
<span><%= link "Edit", to: course_path(@conn, :edit, @course) %> </span>
<span><%= link "Back", to: course_path(@conn, :index) %> </span>